title: <p align="center"> Nguyen Dao Linh Dan </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/linh-dan-undefined-b04a752b9/">LinkedIn</a> |
  <a href="https://github.com/LinhDancute">GitHub</a>
  </p>
  
  <p align="justify">
  I am junior student of Information Technology, majoring in Software Engineer at Saigon University.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
